FROM node:7.10-onbuild

RUN useradd -m -s /bin/false app
ENV HOME=/home/app

ENV REFRESHED_AT=2017-05-29

USER root
RUN npm install pm2 -g

ADD package.json npm-shrinkwrap.json $HOME/
RUN chown -R app:app $HOME/*

WORKDIR $HOME
RUN npm install --only=prod

COPY . $HOME