FROM node:7.10-onbuild

RUN useradd -m -s /bin/false app
ENV HOME=/home/app

ENV REFRESHED_AT=2017-05-29

USER root

COPY package.json npm-shrinkwrap.json $HOME/
RUN chown -R app:app $HOME/*

USER app

WORKDIR $HOME
RUN npm install