node-backend-boilerplate:
  build: .
  dockerfile: Dockerfile-dev
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app
    - /home/app/node_modules
  entrypoint: npm start